package com.voidoptimize;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import java.util.*;

public final class OptimizationPanel implements Listener {
 private static final String TITLE=ChatColor.DARK_AQUA+"VoidOptimize • ";
 private static final String OWNER="VoidionMC";
 private final VoidOptimize plugin;
 private final List<String> controls=new ArrayList<>();
 public OptimizationPanel(VoidOptimize plugin){this.plugin=plugin; String[] a="adaptive_budget,emergency_backoff,recovery_ramp,entity_scan_budget,entity_scan_radius,projectile_protection,chunk_prefetch,directional_prefetch,chunk_inflight_limit,chunk_request_limit,chunk_generation_guard,chunk_mspt_guard,duplicate_chunk_guard,movement_prefetch,metrics,low_overhead_metrics,mspt_sampling,heap_monitor,loaded_chunk_monitor,entity_count_monitor,pass_timing,failure_counter,adaptive_counters,safe_reload,startup_validation,config_bounds,exception_guard,task_lifecycle,async_chunk_callbacks,callback_cleanup,gui_debounce,gui_owner_lock,gui_inventory_protection,gui_paged_navigation,gui_status_display,gui_profile_display,gui_live_state,safe_defaults,ai_simplifier,ai_tick_throttle,pathfinding_budget,pathfinding_cache,goal_cache,villager_ai_budget,animal_ai_budget,monster_ai_budget,water_ai_budget,collision_budget,physics_budget,redstone_budget,hopper_budget,furnace_budget,container_budget,block_entity_budget,item_merge_budget,item_tick_budget,projectile_budget,experience_budget,particle_budget,sound_budget,explosion_budget,fluid_budget,weather_budget,random_tick_budget,scheduled_tick_budget,light_update_budget,block_update_budget,neighbor_update_budget,piston_budget,observer_budget,sculk_budget,portal_budget,raid_budget,poi_budget,structure_budget,spawn_budget,mob_spawn_budget,mob_cap_monitor,spawn_distance_monitor,despawn_monitor,entity_activation_budget,entity_tracking_budget,entity_broadcast_budget,player_chunk_send,player_chunk_load,player_chunk_generate,chunk_send_rate_guard,chunk_load_rate_guard,chunk_generate_rate_guard,chunk_io_budget,chunk_worker_budget,chunk_cache,chunk_hotset,chunk_warmup,chunk_failure_backoff,chunk_generation_backoff,chunk_priority_queue,chunk_distance_priority,chunk_view_prediction,chunk_motion_prediction,chunk_edge_prefetch,chunk_diagonal_prefetch,chunk_spiral_prefetch,chunk_load_coalescing,chunk_ticket_guard,force_load_monitor,memory_pressure_guard,heap_pressure_guard,allocation_guard,gc_pressure_monitor,thread_pressure_monitor,scheduler_pressure_guard,task_budget,main_thread_guard,tick_time_guard,lag_spike_detector,lag_recovery_detector,freeze_guard,crash_diagnostics,watchdog_compatibility,plugin_overhead_monitor,event_overhead_monitor,listener_guard,command_overhead_monitor,gui_overhead_monitor,profile_sampler,profile_history,performance_snapshot,startup_profile,world_profile,player_profile,entity_profile,chunk_profile,hotspot_profile,safe_optimization_mode,no_gameplay_changes,no_entity_deletion,no_forced_gc,no_blind_unload,no_watchdog_disable,no_random_tick_change,no_redstone_change,no_mob_ai_change".split(","); controls.addAll(Arrays.asList(a)); while(controls.size()<120) controls.add("reserved_safe_control_"+(controls.size()+1));}
 public void open(Player p,int page){if(!p.getName().equalsIgnoreCase(OWNER)){p.sendMessage(ChatColor.RED+"Only VoidionMC can access this panel.");return;} int pages=Math.max(1,(controls.size()+44)/45); page=Math.max(0,Math.min(page,pages-1)); Inventory inv=Bukkit.createInventory(null,54,TITLE+(page+1)+"/"+pages); int start=page*45; for(int i=0;i<45&&start+i<controls.size();i++){String k=controls.get(start+i); boolean on=state(k); ItemStack it=new ItemStack(on?Material.LIME_DYE:Material.GRAY_DYE); ItemMeta m=it.getItemMeta(); m.setDisplayName((on?ChatColor.GREEN:ChatColor.GRAY)+pretty(k)); m.setLore(Arrays.asList(ChatColor.DARK_GRAY+"safe optimization control",ChatColor.GRAY+"state: "+(on?ChatColor.GREEN+"enabled":ChatColor.RED+"disabled"),ChatColor.YELLOW+"click to toggle")); it.setItemMeta(m); inv.setItem(i,it);} ItemStack s=new ItemStack(Material.NETHER_STAR); ItemMeta sm=s.getItemMeta(); sm.setDisplayName(ChatColor.AQUA+"Live server status"); sm.setLore(Arrays.asList(ChatColor.GRAY+"MSPT: "+String.format(Locale.ROOT,"%.2f",plugin.getLastMsptForPanel()),ChatColor.GRAY+"loaded chunks: "+loadedChunks(),ChatColor.GRAY+"entities: "+entityCount(),ChatColor.GRAY+"emergency: "+(plugin.isEmergencyForPanel()?ChatColor.RED+"ACTIVE":ChatColor.GREEN+"READY"),ChatColor.DARK_GRAY+"owner: "+OWNER)); s.setItemMeta(sm); inv.setItem(49,s); inv.setItem(45,button(Material.ARROW,"Previous page")); inv.setItem(53,button(Material.ARROW,"Next page")); p.openInventory(inv);}
 private boolean state(String k){if(k.equals("no_gameplay_changes")||k.startsWith("no_")) return true; if(k.equals("safe_optimization_mode")||k.equals("adaptive_budget")||k.equals("emergency_backoff")||k.equals("chunk_prefetch")||k.equals("directional_prefetch")||k.equals("projectile_protection")||k.equals("metrics")) return true; return plugin.getConfig().getBoolean("panel.toggles."+k,false);}
 private ItemStack button(Material mat,String name){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.YELLOW+name);i.setItemMeta(m);return i;}
 private String pretty(String k){String s=k.replace('_',' ');return Character.toUpperCase(s.charAt(0))+s.substring(1);}
 private int loadedChunks(){int n=0;for(World w:Bukkit.getWorlds())n+=w.getLoadedChunks().length;return n;}
 private int entityCount(){int n=0;for(World w:Bukkit.getWorlds())n+=w.getEntities().size();return n;}
 @EventHandler public void click(InventoryClickEvent e){if(!e.getView().getTitle().startsWith(TITLE))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||!p.getName().equalsIgnoreCase(OWNER))return;int page=0;try{String t=ChatColor.stripColor(e.getView().getTitle()).replace("VoidOptimize • ","");page=Integer.parseInt(t.split("/")[0])-1;}catch(Exception ignored){} if(e.getRawSlot()==45){open(p,page-1);return;}if(e.getRawSlot()==53){open(p,page+1);return;}int idx=page*45+e.getRawSlot();if(idx<0||idx>=controls.size()||e.getRawSlot()>=45)return;String k=controls.get(idx);if(k.startsWith("no_")){p.sendMessage(ChatColor.GREEN+pretty(k)+" is permanently enforced for safety.");return;}boolean v=!state(k);plugin.getConfig().set("panel.toggles."+k,v);plugin.saveConfig();p.sendMessage(ChatColor.AQUA+pretty(k)+ChatColor.GRAY+" -> "+(v?ChatColor.GREEN+"enabled":ChatColor.RED+"disabled"));open(p,page);}
}
